### ISSUE TITLE
Add friendly name for patches

### ISSUE THREAD

**Issue by Sculas** [ReVanced/revanced-patcher#100]

**Comment by oSumAtrIX** [comment]
RE: https://discord.com/channels/952946952348270622/953965039105232906/1018625372973174895

**Comment by nwithan8** [comment]
Define "friendly name"?

**Comment by oSumAtrIX** [comment]
> Define "friendly name"?

`Some friendly Name" instead of `some-friendly-name`.

**Comment by Sculas** [comment]
> Define "friendly name"?

Unfriendly name: `microg-support`
Friendly name: `MicroG Support`

**Comment by nwithan8** [comment]
I'm sorry, but I'm not sure where in the application you're seeing that.

I see this when selecting patches:
![Screenshot_20220921-091450.png](https://user-images.githubusercontent.com/17054780/191543204-21bff94a-4260-4639-a9fd-02e71d6b38be.png)

**Comment by masterflitzer** [comment]
but why? friendly names would only introduce confusion and accomplish nothing

**Comment by Sculas** [comment]
Explain me how these two:
- `Microg Support`
- `MicroG Support`
cause any confusion to you.

And they definitely serve a purpose: readability and correctness.

**Comment by masterflitzer** [comment]
when everything here was marked as off topic, this issue should really be closed because i think it was discussed normally (this would make the whole issue off topic)

**Comment by bao000** [comment]
src/test/kotlin/app/revanced/patcher/usage/resource/patch/ExampleResourcePatch.kt

**Comment by Ushie** [comment]
This can be closed, as patch names are friendly by default now
