### ISSUE TITLE
Youtube music can't install

### ISSUE THREAD

**Issue by edzamber** [revanced/revanced-patcher#109]
### Type

Other

### Bug description

Since today Youtube music can't be installed anymore

### Steps to reproduce

Build Youtube music with latest patched and try to install on device

### Relevant log output

```shell
No log
```

### Screenshots or videos

![photo_2022-09-26_18-00-49](https://user-images.githubusercontent.com/16240238/192325267-43401153-d042-40e3-bfda-f517d6d00d6f.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Please use the official CLI guide.

**Comment by edzamber** [comment]
> 

Thanks for reply.

Can you link me official cli guide please ?

**Comment by oSumAtrIX** [comment]
The repository is called `revanced-documentation`.

**Comment by edzamber** [comment]
> The repository is called `revanced-documentation`.

I have double check anything and all seems good.
No way. Youtube music is compiling perfectly but can't install. I have no problem with YouTube vanced. Only with YouTube music. Since a week ago. Before that I have always patch Youtube Music with same way and i always ne able to install it.
