### ISSUE TITLE
bug: can't launch YouTube Revanced app on Huawei Nova 5t

### ISSUE THREAD

**Issue by bbrightvc89** [revanced/revanced-patcher#110]
### Type

Crash

### Bug description

can't launch YouTube Revanced app on Huawei Nova 5t

### Steps to reproduce

Used the Revanced app to do the patch thingy. 

### Relevant log output

```shell
No code
```

### Screenshots or videos

https://user-images.githubusercontent.com/114504244/192567716-062f8b09-21a9-4bb9-b7c3-fcc5ae27d1d2.mp4

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Include proper reproduction steps.
