### ISSUE TITLE
Cannot Update ReVanced: Confilcting Packages

### ISSUE THREAD

**Issue by DovydasTEDS** [revanced/revanced-patcher#114]
### Type

Other

### Bug description

I cannot update revanced but have to reinstall it.

### Steps to reproduce

Step 1: install older revanced
Step 2: install new one without uninstalling
Step 3: error

### Relevant log output

```shell
??
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Reproduction steps are insufficient/ Not a patcher error.
