### ISSUE TITLE
Add a `README.md`

### ISSUE THREAD

**Issue by NatoBoram** [ReVanced/revanced-patcher#12]
Nice project!

I know it's new but it would be beneficial to add some information, a few lines even, about this repo in the `README.md`.

* What's this repo?
* How does it work?
* How to build it?

**Comment by oSumAtrIX** [comment]
Yeah, we will do that eventually. The patcher is mostly done but still subject to change just like everything else, auto docs will follow with the website release, which is why we still work more on finishing the code. In the end we will have full documentation and guidelines for contributions and usage.

**Comment by Aioht** [comment]
I didn't understand if this repo would become like fancied andori app Someday or just my source code I didn't understand please clarify things

**Comment by uzza1hossain** [comment]
Any update on website release?

**Comment by CriticalRange** [comment]
> Nice project!
> 
> I know it's new but it would be beneficial to add some information, a few lines even, about this repo in the `README.md`.
> 
> * What's this repo?
>   * How does it work?
> * How to build it?

Check https://github.com/RevancedTeam/revanced-documentation

**Comment by Sculas** [comment]
@oSumAtrIX Should this be closed?

**Comment by oSumAtrIX** [comment]
No, a proper README is still missing.

**Comment by NatoBoram** [comment]
> Check https://github.com/RevancedTeam/revanced-documentation

Nice 404

**Comment by oSumAtrIX** [comment]
@NatoBoram https://github.com/revanced/revanced-documentation
