### ISSUE TITLE
feat: disable auto update of youtube app only 

### ISSUE THREAD

**Issue by ranasrule** [revanced/revanced-patcher#120]
### Type

Functionality

### Issue

You tube app updates and all patches are lost

### Feature

Some way to detach or disable updates of YouTube app via play store

### Motivation

Will make life easier for users 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Not possible via/task of the patcher.

**Comment by ranasrule** [comment]
> Not possible via/task of the patcher.

Is it possible any other way?
