### ISSUE TITLE
bug: Youtube Revanced 17.43.36 has crashed

### ISSUE THREAD

**Issue by DCTriDev** [revanced/revanced-patcher#122]
### Type

Crash

### Bug description

Youtube Revanced 17.43.36 has crashed when open on Samsung Galaxy S21 Ultra 
Chipset: Exynos 2100
OS: both One UI 4.1 and One UI 5.0
Revanced Manager ver: 0.039
Android Ver: both 12 and 13
Arch: arm64-v8a

### Steps to reproduce

1. Install Youtube latest version on CH Play.
2. Patch Youtube with full patch option.
3. Install Youtube Revanced after patch file apk.
4. Open Youtube Revanced and get crash.

### Relevant log output

```shell
I attach link because It's too much character to submit issue
https://drive.google.com/file/d/1wvYolULP7Y8lgCpCnIabRIQsyZT3gK0q/view?usp=share_link
```

### Screenshots or videos

https://youtu.be/FeQf6WtQSoY

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You are missing installing Vanced MicroG to make the patched app work with root in your reproduction steps.

**Comment by DCTriDev** [comment]
> You are missing installing Vanced MicroG to make the patched app work with root in your reproduction

Thanks for your answer,
I have installed MicroG before and my phone is unroot.

**Comment by oSumAtrIX** [comment]
You are patching a split apk file. You need a full apk.

**Comment by DCTriDev** [comment]
> You are patching a split apk file. You need a full apk.

Thank you so much.

I have solved this issue by patch the downloaded file youtube apk from apkmirror.

Have a nice day!
