### ISSUE TITLE
feat: Kepp and show previouly patched app

### ISSUE THREAD

**Issue by jean-raphael** [revanced/revanced-patcher#128]
### Type

Functionality

### Issue

somme patched app cannot be updated with new app and patch (app not installed), 

when we have this we need to uninstall the previously patched app,

then we need to reinstall the app already patched, but we cannot do this because the app show an open button instead of an install and an open button.

If the manager is killed during the uninstall process we d'ont have any trace off the updated patched app

### Feature

Allow to see (or save) a patched app history and , on each app of the history , allow to install them.

(you may save only one version for each app)

### Motivation

this feature is to avoid repaching exacly the same app with sames patches multiple times.

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This has nothing to do with ReVanced Patcher.
