### ISSUE TITLE
A better way of managing classes to keep memory usage low

### ISSUE THREAD

**Issue by Lucaskyy** [revanced/revanced-patcher#14]
Currently, all classes are read from the input stream, then passed into a `ClassReader` and the returned `ClassNode` is saved in `classes` in `Cache.kt`.

**This is not optimal.** When testing the patcher with the stock YouTube APK, it uses **1300 MB** of RAM.
Remember, the patcher should run on mobile phones!
There's nothing we can do about the allocs and deallocs, that's just the downside of ASM.

To fix this issue, a breaking refactor needs to happen.
We need to read the class and resolve the methods "as we go" when reading the class files from the input stream.
This way we can save the useful classes to memory, and free the classes we don't need.

The bad things about this idea:
- to delete a class, you need to define an empty ClassNode in the list, since our list takes priority over the original JAR. we can add helper methods for this, though.
- referencing classes that are not referenced by the signatures will not work, since they are dropped

The good things about this idea:
- less memory usage! we only store the classes that are referenced by the signatures.

If you have suggestions, better ideas, or really just anything, please let me know!

**Comment by oSumAtrIX** [comment]
Note, patches referencing other classes is inevitable, but deleting classes is not necessary. In that case we have to resolve all referenced classes at some point, maby a patch can return all classes which it has been using

**Comment by Lucaskyy** [comment]
> Note, patches referencing other classes is inevitable

This is fine as long as these other classes have a signature belonging to them. So if PatchA references classB, then classB must have a signature in the signature array. Otherwise it will be dropped.
