### ISSUE TITLE
bug: Off-by-one in "removeInstructions" extension function

### ISSUE THREAD

**Issue by rstular** [revanced/revanced-patcher#166]
### Type

Other

### Bug description

The method is [implemented](https://github.com/revanced/revanced-patcher/blob/main/src/main/kotlin/app/revanced/patcher/extensions/Extensions.kt#L41-L45) as

```kotlin
fun MutableMethodImplementation.removeInstructions(index: Int, count: Int) {
    for (i in count downTo 0) {
        this.removeInstruction(index + i)
    }
}
```

Since Kotlin ranges are inclusive on both ends, it causes an extra instruction to be deleted for any given count.

### Steps to reproduce

Call `removeInstructions(0, 5)` on a mutable method, and observe that 6 instructions get deleted.

### Relevant log output

```shell
N/A
```

### Solution

As Kotlin doesn't have a comparable `downTo` operator which would exclude one end of the range, the easiest way to fix this is probably to just decrement the count before creating the range.

### Additional context

Some patches use the current implementation of the `removeInstructions` function, namely:

 - Twitter [`HideViewsBytecodePatch`](https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/twitter/layout/hideviews/patch/HideViewsBytecodePatch.kt)
 - TwelveWidgets [`UnlockPaidWidgetsPatch`](https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/twelvewidgets/unlock/patch/UnlockPaidWidgetsPatch.kt)
 - TickTick [`UnlockThemePatch`](https://github.com/revanced/revanced-patches/blob/main/src/main/kotlin/app/revanced/patches/ticktick/misc/themeunlock/patch/UnlockThemePatch.kt)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by badawoll** [comment]
This can be closed (was resolved in  #167)
