### ISSUE TITLE
Provide more information in the install/patch logs

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-patcher#173]
### Type

Functionality

### Issue

Patch logs does not show the pkgName/version used to patch. When install/patch fails people usually do a screenshot and ask for help.

### Feature

Showing the pkg name / version patched at both the start phase (initializing installer) and the final phase (Finished). Sth like this:

```
Initializing Installer
patching <package name> @<version>
...
Finished patching <package name> @<version>!
```

### Motivation

This can provide more information when doing tech support

### Additional context

Transferred from revanced/revanced-manager#852

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
To keep the purpose minimal to the cause, this can be implemented in whatever supplies the APK to ReVanced Patcher.
