### ISSUE TITLE
bug: patched twitter apk fails to install

### ISSUE THREAD

**Issue by twig** [revanced/revanced-patcher#180]
### Type

Crash

### Bug description

Apologies if this falls under another part of Revanced projects, but I'm not fully across how it all glues together.

Existing twitter app already uninstalled

I downloaded the recommended twitter apk from apkmirror (9.71.0 at time of writing) and patched 2 things (in Revanced manager via storage)

* Hide ads
* remove screenshot restrictions

Process completes, click install (non root method) but install fails with "app not installed"

![Screenshot_20230528-130207](https://github.com/revanced/revanced-manager/assets/59689/cc58eab6-379c-41a5-a58e-a2c387b90fac)

Decice info
![Screenshot_20230528-130348](https://github.com/revanced/revanced-manager/assets/59689/648ccb73-7e18-4091-baa1-3187e996637c)

Anything else I can help with debugging the issue?

### Steps to reproduce

Download APK, select from storage to patch, select hide ads and screenshot restrictions, patch, install non-root method

### Relevant log output

```shell
?
```

### Screenshots or videos

Recording 
https://github.com/revanced/revanced-manager/assets/59689/e0f6be0e-c23b-4c62-8e27-c8666892d253

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ILoveOpenSourceApplications** [comment]
Do you already have Twitter installed in your phone? If so you'll have to uninstall it before installing the patched version of Twitter.

**Comment by twig** [comment]
Nope I uninstalled it prior to patching to avoid any signature issues

**Comment by twig** [comment]
Hmm no, but I'll give that a shot tonight

**Comment by twig** [comment]
Additional information, logs say it failed to rename package

![Screenshot_20230607-180001.jpg](https://github.com/revanced/revanced-patcher/assets/59689/58751d9a-cf5f-4e44-a186-a00fc4a046d6)

**Comment by ILoveOpenSourceApplications** [comment]
> Additional information, logs say it failed to rename package

Change package name can only be done when patching through CLI. It's not possible via the Manager, atleast for now.

**Comment by twig** [comment]
Ah right

Oh install succeeded normally this time. I didn't do anything different to before. Wonder what happened

**Comment by twig** [comment]
Hmm either that or there's a weird issue when saving patched apk to storage first.

Either way, happy to close this off

**Comment by twig** [comment]
Interesting, it was working great with no ads for a while

I rebooted my phone and patched Twitter app keeps crashing on startup

Trying to reinstall the patched apk fails too. Any idea how to figure out where it's failing?

**Comment by ILoveOpenSourceApplications** [comment]
Did you install Twitter as root?

**Comment by twig** [comment]
Nope it was never installed as root

Nothing is currently installed with the same package name

**Comment by oSumAtrIX** [comment]
Twitter patches don't change the package name, a forced Google PlayStore update will override it. If it's crashing, then open a new issue with crash logs

**Comment by twig** [comment]
New issue created at https://github.com/revanced/revanced-patcher/issues/188

I've attached relevant ADB logs which might help narrow down the issue
