### ISSUE TITLE
bug: Cant apply certain patches

### ISSUE THREAD

**Issue by dpoettler** [revanced/revanced-patcher#181]
### Type

Crash

### Bug description

When i try to patch Tiktok some patches do not work. (Settings, Downloads, Feed-Filter)

### Steps to reproduce

1. Use APK-Mirror Tiktok apk
2. Select it in Revanced Manager
3. Select recommended patches
4. Try to patch
5. Error

### Relevant log output

```shell
Look at the picture
```

### Screenshots or videos

![Screenshot_20230528_090900](https://github.com/revanced/revanced-patcher/assets/106899369/2445fd90-da5c-4a48-80d9-471db4bd75ff)

### Additional context

I tried it on 4 different versions of the revanced manager

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kazimmt** [comment]
https://github.com/revanced/revanced-patches/issues/2254
