### ISSUE TITLE
Reddit patches not applied to Popular feed

### ISSUE THREAD

**Issue by seirdotexe** [revanced/revanced-patcher#186]
### Type

Other

### Bug description

Any patch applied to Reddit doesn't work on the Popular feed.

### Steps to reproduce

1. Download Reddit apk
2. Patch it
3. Login
4. Go to Popular feed
5. You see promoted posts
6. You see subreddit banner if you open a post from the Popular feed

### Relevant log output

```shell
Not sure, ask if needed!
```

### Screenshots or videos

See reproduce

### Solution

Figure out why the patches don't apply to the Popular feed

### Additional context

I'm not the only one who has this.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is not a patcher issue.

**Comment by seirdotexe** [comment]
@oSumAtrIX So what is the issue?

**Comment by seirdotexe** [comment]
> There is none, the patch does not block ads in popular feed, it says that in the description

@oSumAtrIX So what's this? https://github.com/revanced/revanced-patches/pull/2350

**Comment by oSumAtrIX** [comment]
An open pull request awaiting review.
