### ISSUE TITLE
Resource patching 

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-patcher#19]
The new dalvik patcher will only support patching classes. We should extend the framework to patch resources as well

**Comment by Lucaskyy** [comment]
In my opinion this shouldn't be in the Patcher library. Not everyone using the Patcher library needs to patch resources.

**Comment by oSumAtrIX** [comment]
So do we want a seperate resource-patcher? Implementing it into the manager would be out of the managers scope

**Comment by Lucaskyy** [comment]
> So do we want a seperate resource-patcher?

Most likely, yes. It's a lot of project switching, but I think it's the best.

> Implementing it into the manager would be out of the managers scope

I agree.
