### ISSUE TITLE
Vanced MicroG Update

### ISSUE THREAD

**Issue by TheUselessBro** [revanced/revanced-patcher#192]
### Type

Functionality

### Issue

Hi There, I hope you're all doing well.
So, I recently realised that Vanced MicroG is the only thing that enable Non-Root devices to be able to use Revanced for Youtube/Music application.
Ever since the Vanced project was ceased by  Google almost an year ago, it has not been updated.

### Feature

So I would like the ReVanced Team to continue the legacy.
Github for Vanced MicroG: https://github.com/TeamVanced/VancedMicroG

### Motivation

Considering this is very important for Non-Root users, it should be updated frequently.

### Additional context

If I am wrong about anything, or posted in wrong category or you guys know about it already, please forgive me in advance,
Thanks for reading///
Just a User.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
This is not an issue related to Patcher.

**Comment by oSumAtrIX** [comment]
Vanced MicroG is fully functional and does not need a fork
