### ISSUE TITLE
Tiktok Patcher

### ISSUE THREAD

**Issue by m7md7essen** [revanced/revanced-patcher#194]
### Type

Crash

### Bug description

![Screenshot_2023-06-28-11-25-36-382_app revanced manager flutter](https://github.com/revanced/revanced-patcher/assets/32914068/e84aa75c-5364-4c98-b4a8-7009bcf87048)

### Steps to reproduce

1- Download Tiktok Apk.
2- Select Patcher.
3- Select apk file from storage.
4- Select Default Patches.
5- Press Patch.

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Applied disable-login-requirement
Failed to apply downloads: 'downloads' depends on 'settings' but the following error was raised: Hardcoded offset changed.
Failed to apply feed-filter: 'feed-filter' depends on 'settings' but the following error was raised: 'settings' did not succeed previously
Applied fix-google-login
Applied hide-ads
Applied playback-speed
Failed to apply settings: 'settings' did not succeed previously
Applied show-seekbar
Repacking patched apk
Not compiling resources because resource patching is not required
Writing modified dex files
Finished!
```

### Screenshots or videos

![Screenshot_2023-06-28-11-25-36-382_app revanced manager flutter](https://github.com/revanced/revanced-patcher/assets/32914068/c37697de-1108-4f29-83a5-b249a0cf5ff9)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
https://github.com/revanced/revanced-patches/issues/2520#issuecomment-1610982137
