### ISSUE TITLE
Error patching Reddit: AbstractMethodError in close() function 

### ISSUE THREAD

**Issue by lord-ne** [revanced/revanced-patcher#201]
### Type

Other

### Bug description

Trying to re-patch the Reddit app in the manager. It had auto-updated (this removing patches), so I uninstalled and reinstalled it then tried to apply patches. Patching failed with `java.lang.AbstractMethodError: abstract method "void app.revanced.patcher.patch.Patch.close()"` (see full log below). The error indicates that it comes from the patcher, and the Manager GitHub indicates that they don't accept big reports related to patching errors, so I believe this is the correct place for this bug report.

### Steps to reproduce

1. Install Reddit app
2. Try to patch in manager (see selected patches below)

There may be more steps to reproduce this. It's possible that you need to have previously had a patched Reddit, then uninstalled it, then reinstalled from the Play Store and tried to patch again.

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
Unpacking input apk
Reading dex files
Decoding AndroidManifest.xml only, because resources are not needed
Merging integrations
Deleting existing resource cache directory
Decoding resources
Applied hide-ads
Applied premium-icon-reddit
An error occurred! Aborted
Error:
java.lang.AbstractMethodError: abstract method "void app.revanced.patcher.patch.Patch.close()"
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:368)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:326)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Additional context

Running in Manager v1.3.6 on Android 13.

Patching app com.reddit.frontpage v2023.25.1

Patches selected:

* Hide Ads (v0.0.2)
* Premium Icon Reddit (v0.0.1)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Update
