### ISSUE TITLE
bug: patcher claims that `original.apk source file doesn't exist when patching youtube` despite it existing

### ISSUE THREAD

**Issue by BLucky-gh** [revanced/revanced-patcher#205]
### Type

Other

### Bug description

YouTube was annoying me with "uosate available" notifications so I downloaded the latest revanced recommended version from apkmirror and installed it fresh but when patching I an error that I pasted in the relevant logs section in this issue. Note that `original.apk` actually *does* exist at the path in the logs.

### Steps to reproduce

I'm not sure which of these steps are irrelevant but here's how I did it:
1. have a patched youtube installed already
2. get a newer version of the apk from apkmirror
3. install that apk to update youtube (and consequently unpatch it)
4. open revanced manager
5. choose youtube
6. try patching

### Relevant log output

```shell
Initializing installer
Creating working directory
Copying original apk
An error occurred! Aborted
Error:
kotlin.io.NoSuchFileException: /data/adb/revanced/com.google.android.youtube/original.apk: The source file doesn't exist.
	at kotlin.io.FilesKt__UtilsKt.copyTo(Utils.kt:219)
	at kotlin.io.FilesKt__UtilsKt.copyTo$default(Utils.kt:217)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda-20(MainActivity.kt:114)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$Rd-IpIH_jmxD15EWmBEFM-jtGsk(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda13.run(Unknown Source:24)
	at java.lang.Thread.run(Thread.java:1012)
```

### Screenshots or videos

https://github.com/revanced/revanced-patcher/assets/41377306/2f485b58-5e17-43b1-a39b-c08ed3cf227c

### Solution

pressing "Delete temporary files" in settings doesn't help, but using root to open `/data/adb/revanced/com.google.android.youtube/` and delete `base.apk` and `original.apk` with a file manager and then trying to patch again works.

### Additional context

https://discord.com/channels/952946952348270622/1127275480333168640

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
That is an issue with ReVanced Manager, not ReVanced Patcher

**Comment by KobeW50** [comment]
> That is an issue with ReVanced Manager, not ReVanced Patcher

This is one of the checks when submitting a bug report for the Manager. 

![SmartSelect_20230709_103812_Chrome.jpg](https://github.com/revanced/revanced-patcher/assets/84587632/bd22c5df-7f66-4255-902f-af68fa6dc41e)

Can more clarification be given?

**Comment by oSumAtrIX** [comment]
Why, it's an issue with ReVanced Manager, the checkmark does not conflict with it

**Comment by KobeW50** [comment]
> Why, it's an issue with ReVanced Manager, the checkmark does not conflict with it

I think 99% of users would consider this a patching error

![Screenshot_20230708-202955_ReVanced_Manager-1.png](https://github.com/revanced/revanced-patcher/assets/84587632/f3a4c078-a9aa-4e22-968a-5326bfd37dc6)

**Comment by KobeW50** [comment]
@oSumAtrIX or at least "related to patching errors"

**Comment by oSumAtrIX** [comment]
Patching errors refer to errors that are caused by patches unrelated to ReVanced Manager. If you can suggest a better idea, please open a PR for it
