### ISSUE TITLE
feat: youtube material you

### ISSUE THREAD

**Issue by kittenvr** [ReVanced/revanced-patcher#215]
### Type

Cosmetic

### Issue

This would look cool

### Feature

change the theme of youtube to be material you

### Motivation

https://youtu.be/KgoW6R5HqSM
https://www.figma.com/community/file/1069197083803703706/YouTube-Redeisgn-with-Material-You

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kittenvr** [comment]
> This belongs in the ReVanced Patches repository, and there already is a Material You theme (although it's only for accent colors ATM)
> 
> You can use it by using the CLI and selecting it in options.json or waiting for ReVanced Manager to add Patch Options support 

Where do i do youtube revanced feature request then?

**Comment by Ushie** [comment]
"in the ReVanced Patches repository" https://github.com/revanced/revanced-patches

**Comment by kittenvr** [comment]
> "in the ReVanced Patches repository" https://github.com/revanced/revanced-patches

Thx
