### ISSUE TITLE
bug: apply patches in lexicographical order

### ISSUE THREAD

**Issue by inotia00** [ReVanced/revanced-patcher#221]
### Type

Other

### Bug description

The overall issue is the same as the previous issue https://github.com/revanced/revanced-patcher/issues/125
The process of refactoring revanced-patcher seems to be missing the following commits: https://github.com/revanced/revanced-patcher/commit/a306561b55ac848792046378f582a036f7ffab03

### Steps to reproduce

Patch an app with dev branch and check patch order

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![cli](https://github.com/ReVanced/revanced-patcher/assets/108592928/8469c652-7862-406a-8580-1eff27a70995)

### Solution

Restore `.sortBy { it.patchName }` to the following class
https://github.com/ReVanced/revanced-patcher/blob/main/src/main/kotlin/app/revanced/patcher/PatchBundleLoader.kt

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
I am missing proper motivation. Why would you want that?

**Comment by inotia00** [comment]
there is no particular motive

If the missing commit was intentional, it's not a bug, you can close the issue

I just wanted to let the maintainers know about this issue

**Comment by oSumAtrIX** [comment]
It definitely is a regression, though I am not entirely sure why it was even added to begin with
