### ISSUE TITLE
bug: Normal Install bugged

### ISSUE THREAD

**Issue by fawzynahwi** [ReVanced/revanced-patcher#245]
### Type

Crash

### Bug description

Hi, 
I am trying to patch Twitter app and indeed all patches are done successfully but when I attempt to install the patched app the installation dialogue disappears after clicking on "update" and when I install the app with root the twitter app crashes when I try to open an image. 
I am on A13 VoltageOS.
Please help! 

### Steps to reproduce

1-select twitter
2-patch
3-install
4-normal install

### Relevant log output

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Dynamic color succeeded
Hide ads succeeded
Hide recommended users succeeded
Compiling modified dex files
Compiling modified resources
Signing APK
Patched
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
```

### Screenshots or videos

https://github.com/ReVanced/revanced-patcher/assets/52822428/4182320e-d7ce-4c30-8aae-2391465ee4a6

### Additional context

I have tried to reinstall both Twitter and Revanced Manger.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
This is not a patch issue, but a manager issue. Uninstall the installed app before installing the patched app.

**Comment by fawzynahwi** [comment]
> This is not a patch issue, but a manager issue. Uninstall the installed app before installing the patched app.

Sir I have tried that, Twitter just crashes if I open.

**Comment by oSumAtrIX** [comment]
Open a new issue.
