### ISSUE TITLE
bug: install bugged

### ISSUE THREAD

**Issue by fawzynahwi** [ReVanced/revanced-patcher#246]
### Type

Crash

### Bug description

hi,
if I patch twitter app normal install wont work if default app is installed and if I uninstalled the default app and installed the patched one it just FCs. Root install works over default app but it makes the app crash if I open an image.

### Steps to reproduce

1-select twitter
2-patch
3-install

### Relevant log output

```shell
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
Dynamic color succeeded
Hide ads succeeded
Hide recommended users succeeded
Compiling modified dex files
Compiling modified resources
Signing APK
Patched
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
Installing patched file using nonroot method
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Uninstall the installed app before installing the patched app.

**Comment by fawzynahwi** [comment]
> Uninstall the installed app before installing the patched app.

????????
I just told u in previous ticket that its crashing if I do that.

**Comment by oSumAtrIX** [comment]
And I told you to open an issue about the crash.

**Comment by fawzynahwi** [comment]
> And I told you to open an issue about the crash.

What do u call this one????????????????????????????????????
