### ISSUE TITLE
bug?: App crashes at about 2:50am

### ISSUE THREAD

**Issue by GeneralUser-NonDev** [ReVanced/revanced-patcher#256]
### Type

Crash

### Bug description

Not that I watch Youtube alot in the wee-hours if the morning but, the last couple times that i have (this morning included) the app shut itself down (crashed without any error dialog?) at 2:50-2:55am mid-video. Could it be a server polling thing or something? not that i know what I'd be looking for but, i didn't see anything out of ordinary in my adguard server or unifi logs. I didn't see this issue mentioned in the issues I'd seen.

### Steps to reproduce

? watch video on app at around 2:50-2:55am?

### Relevant log output

```shell
watched on mobile phone (note20, latest updates), submitting this on my PC
```

### Solution

find reason and fix for crash/closure. 

### Additional context

Device info: 
Samsung Note 20 Ultra (sm-n986u1) with all its latest updates
android ver: 13
supported archs: arm64-v8a, armeabi-v7a, armeabi
app version (in app settings menu, YT version maybe?): 18.23.35
revanced manager info: ver 1.10.3
revanced ver: 18.23.35
non-root
patched Sept 30, 2023
applied patches: 0

This combined with the app not keeping a watch history while connected to my homes wifi is very annoying, not sure of the cause of this issue but that is a seperate entry.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Not a patcher issue, playprotect is killing the app
