### ISSUE TITLE
feat: Native Library patching and File Handle provider for arbitrary files

### ISSUE THREAD

**Issue by Bluebotlabz** [ReVanced/revanced-patcher#265]
### Feature description

It would be extremely useful to support binary patching native libs as well as the ability to obtain a file handle to any file in the APK

This would be especially useful for patching more advanced applications, ie: Google Photos, or patching games, such as Unity games where patching the native libraries could allow for code changes whilst arbitrary file patching would let you modify asset bundles at ease

I think it would be important to provide a file handle rather than the traditional patched API as it may be important to include a custom parser or the ability to create and _delete_ files as needed

### Motivation

This feature should be implemented because it would allow a significant number of apps and games to be patchable through Revanced than otherwise and would allow for further changes to apps than otherwise, especially for games

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
In regards:

- Currently, there are two types of patches: resource and bytecode patches. Out of efficiency, ReVanced Patcher checks if a resource patch is involved and decodes resources to disk for resource patches to modify in that case. In the case of arbitrary files, including libraries, this can happen JIT.

- A new `LibraryPatch` can be added. ReVanced Patcher will pick it up and offer a `context` as a parameter that allows reading and writing libraries in the `/lib` path. To be able to read them, a stream directly to the ZipEntry can be opened. To be able to write them, a stream to the disk should be opened:

    ```kt
	// Opens a File with writing operation to disk and reading operation from ZipEntry
	context["/lib/some.lib"].let { file: File -> 
		// Can open an input stream to read from ZipEntry
		// Can open an output stream to write/cache to disk
	}

	// Later on and in a different patch:

	// Opens a File with writing operation to disk and reading operation from **disk**
	context["/lib/some.lib"].let { file: File -> 
		// Can open an input stream to read from ZipEntry
		// Can open an output stream to write/cache to disk
	}
    ```

- As patches depend on each other, a read operation can be shared, but write operations must be locked. This means if a patch depends on another and another patch opens a write stream without closing it, the patch that depends on it can not open a write stream. When you try, an exception should be raised, similar to what is being done for resources.

- Since libraries can be classified as arbitrary files, a `FilePatch` can be added instead with context to any ZipEntry, not just libraries. Just to let you know, no write access to resources or dex files should be granted, as those are to be modified by other kinds of patches, but read access may be granted.

**Comment by Bluebotlabz** [comment]
You mention a possibility that `LibraryPatch` is _not_ implemented, how would patching libraries work in this case?

**Comment by oSumAtrIX** [comment]
If no `LibraryPatch` is added, `FilePatch` will be able to read and write libraries:

> - A `FilePatch` **MAY** be added for arbitrary files, including libraries if **NO** `LibraryPatch` is added. However, **NO** write access to resources or dex files **SHOULD** be granted, as these are meant to be modified by other kinds of patches. Read access **MUST** be granted.

**Comment by Bluebotlabz** [comment]
That's actually not a bad idea to be honest, and LibraryPatch will probably inherit from FilePatch, though long-term it would be interesting to expand upon it by adding convenient function specific to libraries, such as locating a symbol in a library and such

**Comment by oSumAtrIX** [comment]
A `FilePatch` **MUST NOT**  be open for inheritance as it already offers all implementations that a `LibraryPatch` would need.

**Comment by Bluebotlabz** [comment]
Oh right that makes sense
It would just be a copy of it then

**Comment by Bluebotlabz** [comment]
Couldn't I just implement this by mostly modifying `ResourceContext` and `ResourcePatch` and having it so that it just reads/writes to the streams directly rather than using `DomFileEditor`?
(or probably just an alternative to DomFileEditor that provides direct access to the streams?)

**Comment by oSumAtrIX** [comment]
It will be held in memory unless you do not close the stream. The reason for the closing mechanism is that two patches may attempt to write to the same file which can be a problem.

**Comment by Bluebotlabz** [comment]
Fair, however, I can see this potentially being problematic when trying to patch large files/libraries

Especially stuff like Unity bundles which can exceed sizes in the gigabytes

**Comment by oSumAtrIX** [comment]
The locking mechanism is currently only present when you use DomFileEditor. For input streams, no locking mechanism is needed. The locking process is only necessary when you open a write stream

**Comment by Bluebotlabz** [comment]
Ah, that makes sense so the patch would just, for example, effectively store addresses and data to write at those addresses, then on the close operation, it would just sequentially perform those writes

At the moment I'm mainly just looking into modifying `DomFileEditor` code as a `FileEditor` which will probs implement functions for writing and reading to/from certain addresses...

I do kind of feel like I'm overthinking this though

**Comment by oSumAtrIX** [comment]
DomFileEditor was specifically made for XML and other kinds of DOM files. If you want to open file streams you can currently do so with context["file"].inputStream()

**Comment by Bluebotlabz** [comment]
wait is that actually currently implemented or are you just proposing implementation?

**Comment by oSumAtrIX** [comment]
This is implemented

**Comment by Bluebotlabz** [comment]
oh lol
so strictly speaking, I don't actually need to implement anything for reading, I just need... something for writing

**Comment by Bluebotlabz** [comment]
Also, is there any reason copying the general structure of the `DomFileEditor` but for writing general content to files is a _bad_ idea?

**Comment by oSumAtrIX** [comment]
It was primarily done for DomFileEditor as we would have to introduce custom write and read methods or properly implement all overloads for File if we were want to include the locking mechanism for arbitrary files as well.

**Comment by Bluebotlabz** [comment]
Well didn't you mention that we would need the locking mechanism anyway?

**Comment by oSumAtrIX** [comment]
Your context allows opening read and write streams only. This means that implementing the locking mechanism doesn't require the overhead mentioned in my previous comment as you'd only need to consider the two methods to open read and write streams. Feel free to refactor the code in a way that makes it suitable for arbitrary files as well, the current strategy to just support locking for DomFileEditor is slightly arbitrary and not really ideal.

**Comment by Bluebotlabz** [comment]
Right... Couldn't I also have something like the current `context["file"].inputStream()` stuff but for outputStream and that would be fine?

**Comment by oSumAtrIX** [comment]
context["file"] returns you a `File`, hence no locking mechanism.

**Comment by Bluebotlabz** [comment]
Wait so can't I just use that to patch arbitrary files anyway?

**Comment by oSumAtrIX** [comment]
As it tries to open a file in a directory, but the libraries are not present it would fail. You'd need to read it from the APK file as a stream for example and if you modify it, write back to disk. More particularly you can find the full procedure in my initial comment above

**Comment by Bluebotlabz** [comment]
Oh right, that makes sense

To be honest, whilst it's somewhat jank, as an initial implementation I'll probably just make a modified version of the resource patch

**Comment by zjns** [comment]
So now it's feasible to modify libraries?
