### ISSUE TITLE
bug: YouTube 18.49.37 crash after patch

### ISSUE THREAD

**Issue by yonggamer** [ReVanced/revanced-patcher#267]
### Bug description

YouTube 18.49.37 crash 
before 
[com.google.android.youtube_18.49.37-1541664192_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.z01.zip](https://github.com/ReVanced/revanced-patcher/files/14073651/com.google.android.youtube_18.49.37-1541664192_minAPI26.arm64-v8a.armeabi-v7a.x86.x86_64.nodpi._apkmirror.com.z01.zip)
[com.google.android.youtube_18.49.37-1541664192_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.z02.zip](https://github.com/ReVanced/revanced-patcher/files/14073652/com.google.android.youtube_18.49.37-1541664192_minAPI26.arm64-v8a.armeabi-v7a.x86.x86_64.nodpi._apkmirror.com.z02.zip)
[com.google.android.youtube_18.49.37-1541664192_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.z03.zip](https://github.com/ReVanced/revanced-patcher/files/14073653/com.google.android.youtube_18.49.37-1541664192_minAPI26.arm64-v8a.armeabi-v7a.x86.x86_64.nodpi._apkmirror.com.z03.zip)
[com.google.android.youtube_18.49.37-1541664192_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.z04.zip](https://github.com/ReVanced/revanced-patcher/files/14073654/com.google.android.youtube_18.49.37-1541664192_minAPI26.arm64-v8a.armeabi-v7a.x86.x86_64.nodpi._apkmirror.com.z04.zip)
[com.google.android.youtube_18.49.37-1541664192_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.z05.zip](https://github.com/ReVanced/revanced-patcher/files/14073655/com.google.android.youtube_18.49.37-1541664192_minAPI26.arm64-v8a.armeabi-v7a.x86.x86_64.nodpi._apkmirror.com.z05.zip)
[com.google.android.youtube_18.49.37-1541664192_minAPI26(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.zip](https://github.com/ReVanced/revanced-patcher/files/14073656/com.google.android.youtube_18.49.37-1541664192_minAPI26.arm64-v8a.armeabi-v7a.x86.x86_64.nodpi._apkmirror.com.zip)
after patch
[youtube-revanced_v18.49.37-patches_v4.0.1.z01.zip](https://github.com/ReVanced/revanced-patcher/files/14073642/youtube-revanced_v18.49.37-patches_v4.0.1.z01.zip)
[youtube-revanced_v18.49.37-patches_v4.0.1.z02.zip](https://github.com/ReVanced/revanced-patcher/files/14073643/youtube-revanced_v18.49.37-patches_v4.0.1.z02.zip)
[youtube-revanced_v18.49.37-patches_v4.0.1.z03.zip](https://github.com/ReVanced/revanced-patcher/files/14073644/youtube-revanced_v18.49.37-patches_v4.0.1.z03.zip)
[youtube-revanced_v18.49.37-patches_v4.0.1.z04.zip](https://github.com/ReVanced/revanced-patcher/files/14073646/youtube-revanced_v18.49.37-patches_v4.0.1.z04.zip)
[youtube-revanced_v18.49.37-patches_v4.0.1.z05.zip](https://github.com/ReVanced/revanced-patcher/files/14073647/youtube-revanced_v18.49.37-patches_v4.0.1.z05.zip)
[youtube-revanced_v18.49.37-patches_v4.0.1.zip](https://github.com/ReVanced/revanced-patcher/files/14073648/youtube-revanced_v18.49.37-patches_v4.0.1.zip)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Please open a pull request with logs without splitter zips in the patches repo if you want to report an issue with patches
