### ISSUE TITLE
Patching failed

### ISSUE THREAD

**Issue by seacat17** [ReVanced/revanced-patcher#271]
### Bug description

Fails to patch the application no matter what

### Error logs

[revanced-manager_logcat_20240206202347968309.log](https://github.com/ReVanced/revanced-patcher/files/14185176/revanced-manager_logcat_20240206202347968309.log)

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
That's ReVanced Manager logs, for support move to our social media places, not GitHub issues
