### ISSUE TITLE
feat: Block Youtube videos by category

### ISSUE THREAD

**Issue by Frydesk** [ReVanced/revanced-patcher#287]
### Feature description

Just like the chrome extension [https://chromewebstore.google.com/detail/video-blocker-for-youtube/nedcanggplmbbgmlpcjiafgjcpdimpea?hl=es](url)
There could be an option for block youtube videos by their category (geming, music, vlogs, memes, etc.).

### Motivation

I use the chrome extension for my pc to help me focus on my work and stop wasting time watching trash content in Yoputube, it can save hours of life for the users.

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Patches are to be requested in the patches repo.
