### ISSUE TITLE
bug: Dependencies being added to the set of executed patches

### ISSUE THREAD

**Issue by ILoveOpenSourceApplications** [ReVanced/revanced-patcher#300]
### Bug description

Dependencies are being added to the set of executed patches which if closeable are logged: https://github.com/ReVanced/revanced-patcher/blob/main/src/main/kotlin/app/revanced/patcher/Patcher.kt#L252

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by ILoveOpenSourceApplications** [comment]
Hey @oSumAtrIX, I'm still seeing the dependencies while patching now as well.

**Comment by oSumAtrIX** [comment]
Did you use the release of Patcher that fixes it

**Comment by ILoveOpenSourceApplications** [comment]
The manager fetches the latest release right?

**Comment by oSumAtrIX** [comment]
No. It uses the version it was compiled with.

**Comment by ILoveOpenSourceApplications** [comment]
I am currently using the latest version of ReVanced Manager, v1.21.2. So when will it be fixed for the manager?

**Comment by oSumAtrIX** [comment]
Whenever it uses the release of Patcher that fixes it
