### ISSUE TITLE
Remove the annoying 'Recent tweets' pop-up from X

### ISSUE THREAD

**Issue by nadiration** [ReVanced/revanced-patcher#305]
### Feature description

When you're are browsing the tweets there's this annoying popup that tells you to about new tweets and it's very distracting and annoying because it pops up like every 15 seconds. Very distracting.

Thank you for your attention.

### Motivation

The pop-up is very distracting and makes the overall UX of the app bad.
![Screenshot_20240816-164133_X](https://github.com/user-attachments/assets/a9e5acec-ac88-41b5-8637-835e48491067)

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is the patcher and not the patches repo.
