### ISSUE TITLE
feat: Update support for newer versions of apps for patch like Youtube

### ISSUE THREAD

**Issue by karthikvijay5227** [ReVanced/revanced-patcher#307]
### Feature description

The app still supports much old version of youtube for patching please upgrade the patch for newer version.

### Motivation

New UI and fixes available in newer version of apps like youtube

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Send a screenshot for what you wrote in the motivation part
