### ISSUE TITLE
feat: provide api to search multiple fingerprints which condition matched

### ISSUE THREAD

**Issue by zjns** [ReVanced/revanced-patcher#308]
### Feature description

Sometimes, I need to search multiple fingerprints which condition matched, since patcher not provide api like it, I write [MultiMethodBytecodePatch.kt](https://github.com/BiliRoamingX/BiliRoamingX/blob/main/patches/src/main/kotlin/app/revanced/patches/bilibili/patcher/patch/MultiMethodBytecodePatch.kt) and [MultiMethodFingerprint.kt](https://github.com/BiliRoamingX/BiliRoamingX/blob/main/patches/src/main/kotlin/app/revanced/patches/bilibili/patcher/fingerprint/MultiMethodFingerprint.kt) to implements it. So now I wish patcher provide api like it.

### Motivation

Bilibili developers sometimes develop multiple similar sets of codes for the same function to conduct AB test, which need to be processed simultaneously.

### Acknowledgements

- [X] I have checked all open and closed feature requests and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
What's a use case for this?

**Comment by zjns** [comment]
Bilibili developers sometimes develop multiple similar sets of codes for the same function to conduct AB test, which need to be processed simultaneously.

**Comment by zjns** [comment]
In my project, there are 11 similar fingerprints.
![QQ_1725784218534](https://github.com/user-attachments/assets/4888cd41-665a-46f2-981e-669d575730bc)

**Comment by oSumAtrIX** [comment]
Hm, this sounds like a very specific use case. Usually you'd create a fingerprint abstract class and then implement the differences into multiple fingerprints, the resolve those. I'd say this is good enough. A fingerprint matching multiple methods would need a bit of a design overhaul, like docs, breaking changes, some considerations about performance and so on, so for now I'd say this solution is good enough. Open for reconsideration though, thanks anyway.

**Comment by zjns** [comment]
But with DSL API, I can't seem to extend `BytecodePatch` as easily as before to achieve the same effect.

**Comment by oSumAtrIX** [comment]
The same can be achieved functionally:

fun myFingerprint(block: FingerprintBuilder.() -> Unit) = fingerprint {
 // Add your super stuff here
 block()
}

**Comment by zjns** [comment]
Obviously, this won’t work. I need to write another fingerprint implementation for the situation at least.

**Comment by oSumAtrIX** [comment]
Why wouldn't it work?
