### ISSUE TITLE
bug: `BytecodeContext#findClass(String)` Can find the wrong class

### ISSUE THREAD

**Issue by LisoUseInAIKyrios** [ReVanced/revanced-patcher#309]
### Bug description

Currently `findClass` works by only checking for contains:

```
    /**
     * Find a class by a given class name.
     *
     * @param className The name of the class.
     * @return A proxy for the first class that matches the class name.
     */
    fun findClass(className: String) = findClass { it.type.contains(className) }

```

But this can cause issues where the class desired is a substring of another class:

`Labc;`
`Labcdefg;`

Calling `context.findClass("abc")` could return either `abc` or `abcdefg`

### Solution

Check for exact class name using == (and not contains):
`fun findClass(className: String) = findClass { it.type == className }`

Or if it's desirable to allow specifying class name only and not package, then maybe check with something like:
```
// Untested code, theoretical fix:
fun findClass(className: String) {
        if (className.startsWith('/')) {
            return it.type == "L$className;"
        }
        
        return it.type.endsWith("/$className;")
    }
```

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Looks like it could cause breaking changes in case someone already relies on this behavior. I think the API isn't that necessary since you have access to the class list and therefore can already find a class using any predicate you want. Therefore I'll consider deprecating the API

**Comment by oSumAtrIX** [comment]
you can use `context.classes.first { }`
