### ISSUE TITLE
bug: TikTok Patching gets stuck

### ISSUE THREAD

**Issue by sorpyrbs** [ReVanced/revanced-patcher#313]
### Bug description

ReVanced gets stuck on "Compiling patches dex files" (idk if I spelt it correctly), while patching tiktok from an apkmirror apk, I used the suggested version too
Device: Galaxy S24 Ultra
Android: 14
One UI v: 6.1

### Additional context

![Image](https://github.com/user-attachments/assets/424f9ad6-e13a-401f-b618-bd313bde9d7a)

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Same as OOM #193
