### ISSUE TITLE
feat: Allow viewing patches per app in Patcher view

### ISSUE THREAD

**Issue by Blend3rman** [ReVanced/revanced-patcher#320]
### Feature description

The patcher should allow users to pre-view what patches are available for a particular app **regardless of whether it's installed, or whether an APK file is available locally.**

### Motivation

This would allow users to stay on the ReVanced Manager for all their patch lookups, instead of needing to visit the patches GitHub. There is already a great "search the internet for APK" feature, and I feel this patch view feature would combo well with it.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
This is the repo for the patcher library, not ReVanced Manager.
