### ISSUE TITLE
feat: Aurora Store Integration for Downloads

### ISSUE THREAD

**Issue by Hate9** [ReVanced/revanced-patcher#324]
### Feature description

Aurora Store has the ability to download specific versions of apps.
Optional intent-based integration with the Aurora Store app could function as a much more user-friendly alternative to the current web search feature for downloading the recommended version of apps when patching.

### Motivation

While ReVanced is very usable for more technically-inclined users, it is still less usable for less technically-capable users, and less usable for such users than browser-based adblock solutions. I think that this feature, or a feature like it, could be an excellent step in the direction of increased usability for this target group.

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
ReVanced Patcher is specifically for patching and not downloading apps. That would be something for Manager. Aurora store serves split apks, unusable for ReVanced.

**Comment by Hate9** [comment]
Oh dear, I must have gotten confused between Manager and Patcher! Sorry!
