### ISSUE TITLE
feat: Add option to use old revanced patches

### ISSUE THREAD

**Issue by MrHuaweiFan** [ReVanced/revanced-patcher#328]
### Feature description

Just add an option to import .rvp files, and use old patches instead of the current one. 

### Motivation

I think its a pretty neat and basic option to have

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
As long as no breaking changes are done, you can use older patches via CLI. ReVanced Manager uses the API and the new version will allow selecting files locally.
