### ISSUE TITLE
Root version not installed

### ISSUE THREAD

**Issue by Foxydroid** [revanced/revanced-patcher#44]
I wanted to try to install the root version, there is a root. When installed in the console, it says that the program is closing. My YouTube is not a system application, so I can delete it, can you help?

**Comment by oSumAtrIX** [comment]
This is the wrong place. Please follow the documentation or wait until the manager is released.

**Comment by Foxydroid** [comment]
I did everything right according to the documentation. I did it from a PC using adb with root. Windows 11 x64 system. Phone Poco X3 Pro, Android 12, root magisk. Platformtools latest version
