### ISSUE TITLE
Options API for patches

### ISSUE THREAD

**Issue by oSumAtrIX** [revanced/revanced-patcher#61]
# Issue 

Currently, patches are static and do not provide any options.

# Proposal

Add an API to allow patches to supply options of primitive type.

# Implementation Idea

The patcher will provide an abstract `PatchOption`.

### Example:

```kotlin
val option: PatchOption = StringOption(default = null, required = false, description = null, title = null)

assert(option.default == null)
option = "value" // Operator overloading
assert(option == "value")
```

The patch interface will be extended to provide an internally visible collection of options.

### Example:
```kotlin
BytecodePatch(options = listOf(stringOption1, stringOption2, booleanOption3), ..)
```

## Alternative

As an alternative, PatchOptions can be annotations.

**Comment by Sculas** [comment]
Now that you have specified the book's contents, what about the cover?

We work with patch bundles here. We only have generic classes, we can't access them.
So, if we look from the CLI perspective, how would this work in your mind?

When designing this API change, we not only need to think about the book's contents, but also the cover and how people are going to use it.

**Comment by oSumAtrIX** [comment]
The bundles have nothing to do with it. A patch can provide a list of patch option instances which the cli or manager can access and when the patcher executes the patch, the patch can access the options to read its settings.

**Comment by Sculas** [comment]
Could you provide a code example of that?

**Comment by oSumAtrIX** [comment]
Not yet, the implementation can be discussed later.

**Comment by oSumAtrIX** [comment]
currentPatch.options.forEach { showAndConfigure(it) }
patcher.add(currentPatch)
patcher.execute()
