### ISSUE TITLE
{Patch Request} Make The Choose Quality Popup boxed like the settings box.

### ISSUE THREAD

**Issue by AdishSagarawat** [revanced/revanced-patcher#67]
This is boxed...

![174068190-6398ece2-2fc7-47e4-899e-7529a9b30bdf](https://user-images.githubusercontent.com/69076256/178114167-664df8d8-367d-4622-af0b-9d1a2ab3e73b.jpg)

Make this boxed also.... (along with other submenus also)
![174068263-d994b94e-ee1a-46fc-a693-5abf8cd5da75](https://user-images.githubusercontent.com/69076256/178114253-4dca1c79-d479-4c19-8425-66f92c234cdd.jpg)

**Comment by oSumAtrIX** [comment]
Wrong place to request.
