### ISSUE TITLE
[Patch Request] Make , the (resolution) will apply to current video notification popup box centred and black.

### ISSUE THREAD

**Issue by AdishSagarawat** [revanced/revanced-patcher#68]
![174067541-5f8daea9-2a2e-482b-982e-b8a3e1a1327c](https://user-images.githubusercontent.com/69076256/178114371-fb22532b-8441-4df4-b9b7-785a6b198f54.jpg)

This should be centered and black.

**Comment by oSumAtrIX** [comment]
Wrong place to suggest, once again, please stop suggesting on this repo.
