### ISSUE TITLE
feat: duplicates scanning for fingerprints

### ISSUE THREAD

**Issue by ghost** [ReVanced/revanced-patcher#74]
## 🐞 Issue

Currently fingerprints resolve to the first thing found that matches.
This can be unsafe, for example if a fingerprint matches multiple places -> wrong stuff is getting patched -> app crashes at runtime.

## ❗ Solution

Patcher should have the ability to make sure fingerprints are unique and only find exactly one specific thing.

## ❓ Motivation

Make sure fingerprints find one thing and warn devs in case something is not unique anymore.

## ⚠ Additional context

Initial discussion because of fingerprints "safety":
https://github.com/revanced/revanced-patches/pull/239

---

## Performance + CLI

For performance reasons the duplicates checking should be disabled by default (when patching known to work versions).

The CLI should not scan for duplicates for patching supported versions.
However when `--experimental` flag is enabled it could make use of duplicate checking.

**Comment by oSumAtrIX** [comment]
I think this can be done by cloning the fingerprint, and after it matches, add the match to a list, then create a sublist of the classes and match the new clone in it.
