### ISSUE TITLE
feat: only do resource patching when required

### ISSUE THREAD

**Issue by bogadana** [revanced/revanced-patcher#76]
### Type

Functionality

### Issue

Currently the user has to manually specify whether resource patching should be enabled. 

### Feature

Choosing automatically based on whether any resource patches are selected removes the unnecessary manual choice.

### Motivation

Disabling resource patching when not required saves a lot of time.

**Comment by bogadana** [comment]
And before you ask this can't easily be done in cli because of dependencies

**Comment by Aunali321** [comment]
Same case with manager ^

**Comment by oSumAtrIX** [comment]
> And before you ask this can't easily be done in cli because of dependencies

Why?

**Comment by bogadana** [comment]
> > And before you ask this can't easily be done in cli because of dependencies
> 
> Why?

Are dependencies accessible without an instance?

**Comment by oSumAtrIX** [comment]
Yes, you have access to the classes annotations before having to create an instance of the class.

**Comment by bogadana** [comment]
Still I think it makes more sense in patcher. There's no reason to give it resource patches and then disable resource patching. Would avoid duplicate code between the cli/manager too
