### ISSUE TITLE
video start over 

### ISSUE THREAD

**Issue by erez669** [revanced/revanced-patcher#78]
### Type

Other

### Bug description

when video is finish, it start over again, i want to change that video done and won't start again and i can't find any option to change this

### Steps to reproduce

watching video

### Relevant log output

```shell
don't have any log
```

### Solution

add settings

**Comment by Canny1913** [comment]
Wrong repository.

**Comment by oSumAtrIX** [comment]
Disable auto repeat patch.

**Comment by erez669** [comment]
ok, but how?

**Comment by TheJeterLP** [comment]
> ok, but how?

Read docs and don't use prebuilt apk files.
