### ISSUE TITLE
feat: <title> Can I see Shorts on Revance?

### ISSUE THREAD

**Issue by sH1222J** [revanced/revanced-patcher#79]
### Type

Functionality

### Issue

Shorts are not visible on the Galaxy Tab.

### Feature

I can watch Shorts in the original YouTube app.

is it possible to see Shorts in Revance?

### Motivation

I can watch Shorts in the original YouTube app.

**Comment by oSumAtrIX** [comment]
Disable the patch to hide the shorts button.
