### ISSUE TITLE
Revanced App not supporting download

### ISSUE THREAD

**Issue by html-css-js-art** [revanced/revanced-patcher#86]
### Type

Other

### Bug description

Not supporting to download higher quality video .

### Steps to reproduce

NA

### Relevant log output

```shell
nolog
```

### Screenshots or videos

![Screenshot_2022-08-09-08-25-16-43](https://user-images.githubusercontent.com/61317144/183554080-4b62dd75-cfd5-40ca-968b-ce644bc4914c.jpg)

**Comment by Itroublve** [comment]
This isn't a bug, it's a feature request! Also this is not the right repo to report bugs with (non existent) patches either.
