### ISSUE TITLE
bug: MethodFingerprint resolved wrong method when there were multiple methods with same name in a class.

### ISSUE THREAD

**Issue by d4rkk3y** [revanced/revanced-patcher#95]
### Type

Other

### Bug description

I get this bug when try to create a fingerprint of a method which is in a class have another same name but different parameters number or type.
I think the problem because of this method
https://github.com/revanced/revanced-patcher/blob/44f6a3ebc56cebfd9201f7d244fa1f233a54942f/src/main/kotlin/app/revanced/patcher/fingerprint/method/impl/MethodFingerprint.kt#L67-L71
call
https://github.com/revanced/revanced-patcher/blob/44f6a3ebc56cebfd9201f7d244fa1f233a54942f/src/main/kotlin/app/revanced/patcher/extensions/Extensions.kt#L54-L60

### Steps to reproduce

1. Create a fingerprint of a method which have same name with another method in that class.
2. Resolve the method.
3. MethodFingerprint.result is point to the method which have same name and lower index of the needed method.

### Relevant log output

```shell
no log
```

**Comment by oSumAtrIX** [comment]
Can you provide sample code which fails according to you?

**Comment by d4rkk3y** [comment]
This is the pull request of the patch that can produce the issue. 
https://github.com/revanced/revanced-patcher/issues/95#issue-1359831135
The resolve mutableMethod will be different from method that resolve from fingerprint because of the mutableMethod use softComareTo.
https://github.com/d4rkk3y/revanced-patches/blob/b953b0bb89d7089be5f6fbe3af5257c04b61a1ac/src/main/kotlin/app/revanced/patches/tiktok/ad/patch/TiktokAdsPatch.kt#L58-L62

**Comment by d4rkk3y** [comment]
Afaik, we can fix this by check both method name and parameters for not only constructor but also the normal method because in a class it possible to have 2 method which have same name but different parameters number and type.
